"""Shipped. image desk: fresh, relevant, licensed images for every issue. Never recycled.

For each image slot in an issue (cover, lead, one per Also Shipped story):
  1. SCENE    Claude reads the issue and names a concrete, photographable subject per slot,
              with Commons search queries and a fallback generation prompt.
  2. SOURCE   Wikimedia Commons search; keep only public domain, CC0 and CC BY (no share-alike,
              no AI-generated uploads), big enough for the slot, and never used before
              (ledger match on source URL or perceptual hash).
  3. PICK     Claude picks the candidate that actually fits the story, or none.
  4. GENERATE When nothing fresh fits, OpenAI generates one. Generated images never show real
              people, real named places, logos or text, and are always credited
              "Illustration, AI-generated" so they cannot pass for news photos.
  5. PRESS    image-press.py renders orange ink (cover: halftone + Atkinson fallback; rest:
              Atkinson), auto-exposed, logged PENDING for human review.
  6. LEDGER   every chosen source is recorded in content/image-ledger.json so no later issue
              can reuse it.

usage:
  python image-desk.py ISSUE_MD [--no-generate] [--model sonnet] [--rethink] [--fresh]
  then: python image-press.py review content/articles/issue-NN/images
  redo: python image-press.py reject <images> story-1-atkinson.png --by Eddie --note "wrong country"
        python image-desk.py ISSUE_MD        (only rejected slots are re-sourced; that source never returns)

Needs: numpy + Pillow (press, perceptual hash), `claude` CLI, OPENAI_API_KEY for generation.
Writes: content/articles/issue-NN/images/{src/, slots.json, credits.json, manifest.json, *.png}
"""
import sys, os, re, json, time, base64, hashlib, argparse, subprocess, datetime, urllib.parse, urllib.request, urllib.error, io

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
CONTENT = os.path.normpath(os.path.join(HERE, "..", "..", "content"))
LEDGER = os.path.join(CONTENT, "image-ledger.json")
UA = "ShippedImageDesk/1.0 (id8labs.app/shipped)"
ALLOWED = re.compile(r"^(public domain|pd|cc0|cc by(?!-sa)\b)", re.I)
AI_UPLOAD = re.compile(r"dall[\s·-]?e|midjourney|stable diffusion|ai[- ]generated|generated by ai", re.I)
GEN_MODEL = "gpt-image-2"
GEN_CREDIT = f"Illustration, AI-generated (OpenAI {GEN_MODEL})"
GEN_RULES = ("Documentary black-and-white photograph style, high contrast, one strong subject, "
             "simple uncluttered background, even light. No real or identifiable people, no real "
             "named places or buildings, no logos, no text, no screens with readable words.")
MIN_W = {"cover": 1800, "lead": 1300, "story": 1100}

# ── issue parsing ─────────────────────────────────────────────────────

def parse_issue(path):
    text = open(path).read()
    fm = {}
    m = re.match(r"^---\n(.*?)\n---\n", text, re.S)
    if m:
        for line in m.group(1).splitlines():
            k, _, v = line.partition(":")
            if v: fm[k.strip()] = v.strip().strip('"')
        text = text[m.end():]
    sections, cur = {}, None
    for line in text.splitlines():
        if line.startswith("## "):
            cur = line[3:].strip(); sections[cur] = []
        elif cur: sections[cur].append(line)
    sections = {k: "\n".join(v).strip() for k, v in sections.items()}
    lead_name = next((k for k in sections if k.lower() in ("investigation", "lead story", "feature")), None)
    lead = sections.get(lead_name, "")
    headline = next((l[2:].strip() for l in lead.splitlines() if l.startswith("# ")), fm.get("title", ""))
    stories = []
    for chunk in re.split(r"^### ", sections.get("Also Shipped", ""), flags=re.M)[1:]:
        title, _, body = chunk.partition("\n")
        stories.append({"title": title.strip(), "text": body.strip()[:1200]})
    num = int(fm.get("issue", re.search(r"issue-(\d+)", path).group(1)))
    return {"issue": num, "title": fm.get("title", ""), "deck": fm.get("deck", ""),
            "open": sections.get("The Open", "")[:1200], "headline": headline,
            "lead": lead[:3000], "stories": stories}

def slots_for(issue):
    s = [{"slot": "cover", "kind": "cover", "context": f"{issue['title']}. {issue['deck']}\n{issue['open']}"},
         {"slot": "lead", "kind": "lead", "context": f"{issue['headline']}\n{issue['lead']}"}]
    for i, st in enumerate(issue["stories"]):
        s.append({"slot": f"story-{i+1}", "kind": "story", "context": f"{st['title']}\n{st['text']}"})
    return s

# ── claude ────────────────────────────────────────────────────────────

def ask_claude(prompt, model):
    out = subprocess.run(["claude", "-p", "--output-format", "json", "--model", model],
                         input=prompt, capture_output=True, text=True, timeout=600)
    if out.returncode != 0: sys.exit(f"claude -p failed: {out.stderr[:400]}")
    res = json.loads(out.stdout)
    txt = res.get("result", "")
    j = txt[txt.find("{"): txt.rfind("}") + 1]
    print(f"  claude ({model}) ${res.get('total_cost_usd', 0):.2f}")
    return json.loads(j)

SCENE_PROMPT = """You are the photo editor of Shipped., a weekly magazine about frontier AI labs.
Images run as orange-ink dithered photographs, so they need ONE clear, concrete, high-contrast subject.
For each slot below, choose a subject that is RELEVANT to that slot's story and photographable
(a real place, object, machine, document, or kind of scene). Every slot must get a DIFFERENT subject;
the cover and lead are the same story, so give them distinct angles. Avoid cliches (glowing brains,
robots, binary code, generic server rooms unless the story is literally about a data center).

Return ONLY JSON:
{"slots":[{"slot":"cover","subject":"...","why":"one line","queries":["3 Wikimedia Commons search queries of 1 to 3 words each, broad enough to return results, most specific first"],"generate":"a prompt for a generated photo of the same subject, with NO real people, NO real named places, NO logos or text"}]}

SLOTS:
"""

PICK_PROMPT = """You are the photo editor of Shipped. For each slot, pick the ONE candidate photo that best fits
the story and the intended subject, or null if none genuinely fits (a near miss is null; we will
generate instead). Prefer clear single subjects that survive heavy dithering.
Write a caption that says LITERALLY what the photo shows (place, object, year if known). Never claim
the photo depicts the news event itself. Never mention colours (every image prints in one orange ink). Also write short alt text.

Return ONLY JSON: {"picks":[{"slot":"cover","choice":<candidate index or null>,"caption":"...","alt":"..."}]}

SLOTS AND CANDIDATES:
"""

GEN_CAPTION_PROMPT = """Write a one-line literal caption and short alt text for each generated illustration below.
Describe what is shown, plainly. Never mention colours (every image prints in one orange ink). Return ONLY JSON: {"captions":[{"slot":"...","caption":"...","alt":"..."}]}

"""

# ── commons ───────────────────────────────────────────────────────────

def http_get(url, timeout=60):
    """GET with backoff: Commons rate-limits bursts (429)."""
    for attempt in range(6):
        try:
            req = urllib.request.Request(url, headers={"User-Agent": UA})
            return urllib.request.urlopen(req, timeout=timeout).read()
        except urllib.error.HTTPError as e:
            if e.code not in (429, 503) or attempt == 5: raise
            wait = int(e.headers.get("Retry-After") or 0) or 4 * (attempt + 1)
            print(f"    commons {e.code}, waiting {wait}s"); time.sleep(wait)

def http_json(url):
    time.sleep(1.0)
    return json.loads(http_get(url, 40))

def strip_html(s):
    return re.sub(r"\s+", " ", re.sub(r"<[^>]+>", "", s or "")).strip()

def commons_search(query, min_w, limit=10):
    q = urllib.parse.urlencode({"action": "query", "format": "json", "generator": "search",
        "gsrnamespace": 6, "gsrlimit": limit, "gsrsearch": f"{query} filetype:bitmap",
        "prop": "imageinfo", "iiprop": "url|size|extmetadata|mime", "iiurlwidth": 2400})
    pages = http_json("https://commons.wikimedia.org/w/api.php?" + q).get("query", {}).get("pages", {})
    out = []
    for p in pages.values():
        ii = (p.get("imageinfo") or [{}])[0]; md = ii.get("extmetadata", {})
        lic = strip_html(md.get("LicenseShortName", {}).get("value", ""))
        cats = md.get("Categories", {}).get("value", "")
        if not ALLOWED.match(lic) or ii.get("width", 0) < min_w: continue
        if ii.get("mime") not in ("image/jpeg", "image/png"): continue
        if AI_UPLOAD.search(p["title"] + " " + cats): continue
        out.append({"title": p["title"].replace("File:", ""), "license": lic,
                    "artist": strip_html(md.get("Artist", {}).get("value", "")) or "Unknown",
                    "desc": strip_html(md.get("ImageDescription", {}).get("value", ""))[:240],
                    "page": ii.get("descriptionurl"), "url": ii.get("thumburl") or ii.get("url"),
                    "width": ii.get("width")})
    return out

# ── freshness ledger ──────────────────────────────────────────────────

def load_ledger():
    return json.load(open(LEDGER)) if os.path.exists(LEDGER) else {"entries": []}

def dhash(img, n=8):
    g = img.convert("L").resize((n + 1, n), Image.LANCZOS)
    px = list(g.get_flattened_data() if hasattr(g, 'get_flattened_data') else g.getdata()); bits = 0
    for y in range(n):
        for x in range(n):
            bits = (bits << 1) | (px[y*(n+1)+x] > px[y*(n+1)+x+1])
    return f"{bits:016x}"

def used_before(ledger, issue, page=None, dh=None):
    for e in ledger["entries"]:
        if e["issue"] == issue: continue          # re-running the same issue may keep its own picks
        if page and e.get("source_page") == page: return True
        if dh and bin(int(e["dhash"], 16) ^ int(dh, 16)).count("1") <= 6: return True
    return False

def fetch(url):
    return http_get(url, 90)

# ── generation ────────────────────────────────────────────────────────

def generate(prompt):
    key = os.environ.get("OPENAI_API_KEY")
    if not key: sys.exit("OPENAI_API_KEY not set; rerun with --no-generate to skip generation")
    body = json.dumps({"model": GEN_MODEL, "prompt": f"{prompt}. {GEN_RULES}", "size": "1536x1024", "n": 1}).encode()
    req = urllib.request.Request("https://api.openai.com/v1/images/generations", data=body,
          headers={"Authorization": f"Bearer {key}", "Content-Type": "application/json"})
    d = json.load(urllib.request.urlopen(req, timeout=300))
    return base64.b64decode(d["data"][0]["b64_json"])

# ── main ──────────────────────────────────────────────────────────────

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("issue_md"); ap.add_argument("--no-generate", action="store_true")
    ap.add_argument("--model", default="sonnet"); ap.add_argument("--rethink", action="store_true")
    ap.add_argument("--fresh", action="store_true", help="redo every slot, not only rejected ones")
    a = ap.parse_args()

    issue = parse_issue(a.issue_md); n = issue["issue"]
    out = os.path.join(CONTENT, "articles", f"issue-{n:02d}", "images"); src = os.path.join(out, "src")
    os.makedirs(src, exist_ok=True)
    slots = slots_for(issue)
    print(f"Issue {n:02d}: {len(slots)} slots")

    # Redo loop: only rejected slots are redone (--fresh redoes all); rejected sources never return.
    prev_manifest = json.load(open(os.path.join(out, "manifest.json"))).get("images", {}) if os.path.exists(os.path.join(out, "manifest.json")) else {}
    prev_credits = json.load(open(os.path.join(src, "credits.json"))) if os.path.exists(os.path.join(src, "credits.json")) else {}
    prev_slots = json.load(open(os.path.join(out, "slots.json"))) if os.path.exists(os.path.join(out, "slots.json")) else {}
    def status(slot):
        st = {e["review"]["status"] for f, e in prev_manifest.items() if f.startswith(slot + "-")}
        return "approved" if st == {"approved"} else ("rejected" if "rejected" in st else "pending")
    keep = set() if a.fresh else {s["slot"] for s in slots if status(s["slot"]) != "rejected" and s["slot"] in prev_credits}
    rejected_path = os.path.join(out, "rejected.json")
    rejected = set(json.load(open(rejected_path))) if os.path.exists(rejected_path) else set()
    rejected |= {prev_credits[s["slot"]]["url"] or prev_credits[s["slot"]]["title"] for s in slots
                 if status(s["slot"]) == "rejected" and s["slot"] in prev_credits}
    json.dump(sorted(rejected), open(rejected_path, "w"), indent=2)
    if keep: print(f"  keeping (approved or pending): {', '.join(sorted(keep))}")
    work = [s for s in slots if s["slot"] not in keep]

    # 1. scene
    scene_path = os.path.join(out, "scene.json")
    if os.path.exists(scene_path) and not a.rethink:
        scene = json.load(open(scene_path)); print("  scene: reusing scene.json (--rethink to redo)")
    else:
        scene = ask_claude(SCENE_PROMPT + json.dumps([{"slot": s["slot"], "story": s["context"][:1500]} for s in slots]), a.model)
        json.dump(scene, open(scene_path, "w"), indent=2)
    by_slot = {x["slot"]: x for x in scene["slots"]}

    # 2. source
    ledger = load_ledger(); cands = {}
    for s in work:
        sc = by_slot.get(s["slot"], {}); found, seen = [], set()
        for q in sc.get("queries", [])[:3]:
            for c in commons_search(q, MIN_W[s["kind"]]):
                if c["page"] in seen or c["page"] in rejected or used_before(ledger, n, page=c["page"]): continue
                seen.add(c["page"]); found.append(c)
        cands[s["slot"]] = found[:8]
        print(f"  {s['slot']:9s} {sc.get('subject','?')[:60]:60s} {len(cands[s['slot']])} fresh candidates")

    # 3. pick
    pick_input = [{"slot": s["slot"], "subject": by_slot.get(s["slot"], {}).get("subject"),
                   "story": s["context"][:500],
                   "candidates": [{"i": i, "title": c["title"], "desc": c["desc"]} for i, c in enumerate(cands[s["slot"]])]}
                  for s in work]
    picks = {p["slot"]: p for p in ask_claude(PICK_PROMPT + json.dumps(pick_input), a.model)["picks"]} if any(cands.values()) else {}

    credits = {k: v for k, v in prev_credits.items() if k in keep}
    slot_meta = {k: v for k, v in prev_slots.items() if k in keep}
    need_caption = []
    entries = [e for e in load_ledger()["entries"] if e["issue"] == n and e["slot"] in keep]
    for s in work:
        name, p = s["slot"], picks.get(s["slot"], {})
        choice = p.get("choice")
        chosen = cands[name][choice] if isinstance(choice, int) and 0 <= choice < len(cands[name]) else None
        data = None
        if chosen:
            data = fetch(chosen["url"])
            dh = dhash(Image.open(io.BytesIO(data)))
            if used_before(ledger, n, dh=dh): chosen = data = None   # same photo under another name
        if chosen:
            credits[name] = {"title": chosen["title"], "credit": f"{chosen['artist']}, {chosen['license']}" if not chosen["license"].lower().startswith(("public domain", "pd")) else "Public domain",
                             "license": chosen["license"], "url": chosen["page"]}
            slot_meta[name] = {"caption": p.get("caption", ""), "alt": p.get("alt", ""), "origin": "photo"}
            print(f"  {name:9s} photo: {chosen['title'][:70]}")
        else:
            if a.no_generate:
                print(f"  {name:9s} no fresh photo fits; skipped (--no-generate)"); continue
            data = generate(by_slot[name]["generate"])
            credits[name] = {"title": by_slot[name]["subject"], "credit": GEN_CREDIT, "license": "generated", "url": None}
            slot_meta[name] = {"caption": "", "alt": "", "origin": "generated"}
            need_caption.append({"slot": name, "subject": by_slot[name]["subject"], "prompt": by_slot[name]["generate"]})
            print(f"  {name:9s} generated: {by_slot[name]['subject'][:60]}")
        img = Image.open(io.BytesIO(data)).convert("RGB")
        img.save(os.path.join(src, f"{name}.jpg"), quality=92)
        entries.append({"issue": n, "slot": name, "source_page": credits[name]["url"],
                        "sha": hashlib.sha256(data).hexdigest()[:16], "dhash": dhash(img),
                        "origin": slot_meta[name]["origin"],
                        "at": datetime.datetime.now().astimezone().isoformat(timespec="seconds")})

    if need_caption:
        for c in ask_claude(GEN_CAPTION_PROMPT + json.dumps(need_caption), a.model)["captions"]:
            slot_meta[c["slot"]].update(caption=c["caption"], alt=c["alt"])

    for name, meta in slot_meta.items():
        meta["subject"] = by_slot.get(name, {}).get("subject")
    json.dump(credits, open(os.path.join(src, "credits.json"), "w"), indent=2)
    json.dump(slot_meta, open(os.path.join(out, "slots.json"), "w"), indent=2)

    # 6. ledger (replace this issue's rows, keep everyone else's)
    ledger["entries"] = [e for e in ledger["entries"] if e["issue"] != n] + entries
    json.dump(ledger, open(LEDGER, "w"), indent=2)

    # 5. press
    press = [sys.executable, os.path.join(HERE, "image-press.py")]
    subprocess.run(press + ["render", src, out, "--halftone", "cover"], check=True)
    subprocess.run(press + ["review", out], check=True)
    print(f"\nReview before publish: {os.path.join(out, 'review.html')}")

if __name__ == "__main__":
    main()
